# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ed0ec53fc3cfa9d739bb61816a5e2c0d811d58dea4a46bdefcfbfe59a9508f9b55ddaf423ed4227700507ff002d6d770e1aa4ba2017df5c820a1128985fd73

test:
  secret_key_base: 900ba8966429940bb6212e7421527e68f64811c34998d871e2f175b33d7656b0b47bc51d60848983c385c605293a98e61ad247bd988aaa3843ecc9261e13c5a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
